version: "2"
services:
  boilerplate-api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/express-rest-es2017-boilerplate
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
